version: '3.10'

services:

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$PASSWORD
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL","pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  
  api:
    build:
      context: .
    command: /bin/bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=$SECRET_KEY
      - DJANGO_ALLOWED_HOSTS=['*']
    tty: false
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  volumes:
    db:
      driver: local
    redis:
      driver: local